### ISSUE TITLE
Define gennaker.yml format

### ISSUE THREAD

**Issue by vgheri** [vgheri/gennaker#5]
The gennaker.yml file contains the deployment pipeline as code.  
Once parsed, it should be a valid deployment pipeline used by the engine to know what to do upon a deploy command is received.

**Comment by vgheri** [comment]
First draft:
```
version: 1
pipeline:
  steps:
     - order: 1
        namespace: int
        autodeploy: true
     - order: 2
        namespace: ppd
        autodeploy: false
        parent: 1
     - order: 3
        namespace: prod
        autodeploy: false
        parent: 2
```
Future ideas: 
`pre-hook` and `post-hook` blocks with actions such as run script, notify via slack etc...
